#!/bin/bash

# Script para visualizar a estrutura completa do projeto

clear
echo "════════════════════════════════════════════════════════════════"
echo "   📁 Concurrency Thread Lab - Project Structure"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📂 ROOT"
echo "├── 📄 pom.xml                      Maven configuration"
echo "├── 📄 .gitignore                  Git ignore rules"
echo "├── 📜 build.sh                    Build script"
echo "├── 📜 run.sh                      Run full benchmark"
echo "├── 📜 run-demo.sh                 Run quick demo"
echo "├── 📜 run-examples.sh             Run examples"
echo "├── 📜 menu.sh                     Interactive menu"
echo "├── 📜 show-structure.sh           This script"
echo "│"
echo "├── 📚 DOCUMENTATION"
echo "│   ├── 📖 README.md               Project overview ⭐"
echo "│   ├── 📖 INDEX.md                Complete index"
echo "│   ├── 📖 QUICKSTART.md           Quick start guide"
echo "│   ├── 📖 CONFIGURATION.md        Configuration guide"
echo "│   ├── 📖 ANALYSIS.md             Results analysis"
echo "│   ├── 📖 ADVANCED_CONCEPTS.md    Deep dive concepts"
echo "│   └── 📖 TROUBLESHOOTING.md      Problem solving"
echo "│"
echo "└── 📂 src/main/java/org/example/"
echo "    ├── 🚀 Main.java               Full benchmark (45 tests)"
echo "    ├── ⚡ QuickDemo.java           Quick demo (12 tests)"
echo "    ├── 🔬 CustomBenchmarkExample.java"
echo "    │"
echo "    ├── 📂 model/"
echo "    │   ├── 📦 Order.java           Order record"
echo "    │   ├── 📊 OrderStatus.java     Status enum"
echo "    │   └── 📈 BenchmarkResult.java Result record"
echo "    │"
echo "    ├── 📂 service/"
echo "    │   └── ⚙️  OrderProcessor.java  I/O, CPU, Mixed processing"
echo "    │"
echo "    ├── 📂 benchmark/"
echo "    │   ├── 🎯 ConcurrencyBenchmark.java (interface)"
echo "    │   ├── 🔵 ExecutorServiceBenchmark.java"
echo "    │   ├── 🟢 VirtualThreadBenchmark.java"
echo "    │   ├── 🟣 CompletableFutureBenchmark.java"
echo "    │   ├── 🟡 ParallelStreamBenchmark.java"
echo "    │   └── 🎬 BenchmarkRunner.java"
echo "    │"
echo "    ├── 📂 report/"
echo "    │   ├── 📺 ConsoleReportGenerator.java"
echo "    │   └── 📊 CsvReportExporter.java"
echo "    │"
echo "    ├── 📂 util/"
echo "    │   ├── 📏 MetricsCollector.java"
echo "    │   └── 🎲 OrderGenerator.java"
echo "    │"
echo "    └── 📂 examples/"
echo "        └── 🎓 ConcurrencyExamples.java"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📊 STATISTICS"
echo "────────────────────────────────────────────────────────────────"
echo "  Java Files:        $(find src/main/java -name "*.java" | wc -l | xargs)"
echo "  Documentation:     $(find . -maxdepth 1 -name "*.md" | wc -l | xargs) markdown files"
echo "  Scripts:           $(find . -maxdepth 1 -name "*.sh" | wc -l | xargs) shell scripts"
echo "  Lines of Code:     $(find src/main/java -name "*.java" -exec cat {} \; | wc -l | xargs)"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "🚀 QUICK COMMANDS"
echo "────────────────────────────────────────────────────────────────"
echo "  ./build.sh         - Compile project"
echo "  ./run-demo.sh      - Quick demo (~30s)"
echo "  ./run.sh           - Full benchmark (~5min)"
echo "  ./run-examples.sh  - Practical examples"
echo "  ./menu.sh          - Interactive menu"
echo "────────────────────────────────────────────────────────────────"
echo ""
echo "📖 START HERE: README.md"
echo ""

